[[language]]
name = "c-sharp"
language-server = { command = "omnisharp", args = [ "--languageserver" ] }
formatter = { command = "dotnet", args = ["csharpier", "--"] }
auto-format = false

[language.config]
"omnisharp.useModernNet" = true
"csharp.inlayHints.parameters.enabled" = true
"csharp.inlayHints.types.enabled" = true
"csharp.inlayHints.types.forImplicitVariableTypes" = true
"csharp.inlayHints.parameters.forLiteralParameters" = true
